diff --git a/C:\Users\980022883\Documents\Codex\2026-09-09\github-plugin-github-openai-curated-remote\script.js b/C:\Users\980022883\Documents\Codex\2026-09-09\github-plugin-github-openai-curated-remote\script.js
new file mode 100644
--- /dev/null
+++ b/C:\Users\980022883\Documents\Codex\2026-09-09\github-plugin-github-openai-curated-remote\script.js
@@ -0,0 +1,20 @@
+const references = [
+ {authors:'Huang TT, Leu D, Zou Y.',title:'Oxidative stress and redox regulation on hippocampal-dependent cognitive functions.',journal:'Arch Biochem Biophys.',details:'2015 Jun 15;576:2-7.',doi:'10.1016/j.abb.2015.03.014',pmid:'25797440',pmcid:'PMC4456256'},
+ {authors:'Franco R, Vargas MR.',title:'Redox Biology in Neurological Function, Dysfunction, and Aging.',journal:'Antioxid Redox Signal.',details:'2018 Jun 20;28(18):1583-1586.',doi:'10.1089/ars.2018.7509',pmid:'29634346',pmcid:'PMC5962327'},
+ {authors:'Aizenman E, Loring RH, Reynolds IJ, Rosenberg PA.',title:'The Redox Biology of Excitotoxic Processes: The NMDA Receptor, TOPA Quinone, and the Oxidative Liberation of Intracellular Zinc.',journal:'Front Neurosci.',details:'2020 Jul 24;14:778.',doi:'10.3389/fnins.2020.00778',pmid:'32792905',pmcid:'PMC7393236'},
+ {authors:'Girouard H, Wang G, Gallo EF, Anrather J, Zhou P, Pickel VM, Iadecola C.',title:'NMDA receptor activation increases free radical production through nitric oxide and NOX2.',journal:'J Neurosci.',details:'2009 Feb 25;29(8):2545-52.',doi:'10.1523/JNEUROSCI.0133-09.2009',pmid:'19244529',pmcid:'PMC2669930'},
+ {authors:'Reyes RC, Brennan AM, Shen Y, Baldwin Y, Swanson RA.',title:'Activation of neuronal NMDA receptors induces superoxide-mediated oxidative stress in neighboring neurons and astrocytes.',journal:'J Neurosci.',details:'2012 Sep 12;32(37):12973-8.',doi:'10.1523/JNEUROSCI.1597-12.2012',pmid:'22973021',pmcid:'PMC3478885'},
+ {authors:'Parellada E, Gassó P.',title:'Activación del glutamato y la microglía como factor desencadenante de la apoptosis dendrítica: un mecanismo fisiopatológico fundamental para comprender la esquizofrenia.',journal:'Transl Psychiatry.',details:'2021;11:271.',doi:'10.1038/s41398-021-01385-9'},
+ {authors:'Garcia-Reyero N, Escalon L, Prats E, Faria M, Soares A, Raldúa D.',title:'Targeted Gene Expression in Zebrafish Exposed to Chlorpyrifos-Oxon Confirms Phenotype-Specific Mechanisms Leading to Adverse Outcomes.',journal:'Bull Environ Contam Toxicol.',details:'2016;96.',doi:'10.1007/s00128-016-1798-3'},
+ {authors:'Sun G, He Y, Chuang D, Lee J, Gu Z, Simonyi A, Sun A.',title:'Integrating Cytosolic Phospholipase A2 with Oxidative/Nitrosative Signaling Pathways in Neurons: A Novel Therapeutic Strategy for AD.',journal:'Mol Neurobiol.',details:'2012;46:85-95.',doi:'10.1007/s12035-012-8261-1'},
+ {authors:'Wilson C, Muñoz-Palma E, González-Billault C.',title:'From birth to death: A role for reactive oxygen species in neuronal development.',journal:'Semin Cell Dev Biol.',details:'2018 Aug;80:43-49.',doi:'10.1016/j.semcdb.2017.09.012',pmid:'28899716'},
+ {authors:'Oswald MCW, Garnham N, Sweeney ST, Landgraf M.',title:'Regulation of neuronal development and function by ROS.',journal:'FEBS Lett.',details:'2018 Mar;592(5):679-691.',doi:'10.1002/1873-3468.12972',pmid:'29323696',pmcid:'PMC5888200'}
+];
+const fullCitation = r => `${r.authors} ${r.title} ${r.journal} ${r.details} doi: ${r.doi}.${r.pmid ? ` PMID: ${r.pmid}.` : ''}${r.pmcid ? ` PMCID: ${r.pmcid}.` : ''}`;
+const list = document.querySelector('#references');
+list.innerHTML = references.map((r,i) => `<article class="reference" style="animation-delay:${i * 55}ms"><div class="ref-number">${String(i+1).padStart(2,'0')}</div><div><p class="authors">${r.authors}</p><h2 class="title">${r.title}</h2><p class="citation"><i>${r.journal}</i> ${r.details}</p><nav class="links" aria-label="Enlaces de la referencia ${i+1}"><a href="https://doi.org/${r.doi}" target="_blank" rel="noopener noreferrer">DOI: ${r.doi}</a>${r.pmid ? `<a href="https://pubmed.ncbi.nlm.nih.gov/${r.pmid}/" target="_blank" rel="noopener noreferrer">PMID: ${r.pmid}</a>` : ''}${r.pmcid ? `<a href="https://pmc.ncbi.nlm.nih.gov/articles/${r.pmcid}/" target="_blank" rel="noopener noreferrer">PMCID: ${r.pmcid}</a>` : ''}</nav></div></article>`).join('');
+const copyButton=document.querySelector('#copyButton'),toast=document.querySelector('#toast');
+copyButton.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(references.map((r,i)=>`${i+1}. ${fullCitation(r)}`).join('\n\n'));toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}catch{toast.textContent='No se pudo copiar automáticamente';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}});
+const themeButton=document.querySelector('#themeButton');
+themeButton.addEventListener('click',()=>{const light=document.body.classList.toggle('light');themeButton.setAttribute('aria-label',light?'Cambiar a modo oscuro':'Cambiar a modo claro');themeButton.querySelector('.theme-label').textContent=light?'Oscuro':'Claro';themeButton.querySelector('span').textContent=light?'☾':'☼';localStorage.setItem('theme',light?'light':'dark')});
+if(localStorage.getItem('theme')==='light')themeButton.click();
